CREATE TABLE IF NOT EXISTS ticks (
  id BIGSERIAL PRIMARY KEY,
  symbol TEXT NOT NULL,
  price NUMERIC NOT NULL,
  timestamp BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGSERIAL PRIMARY KEY,
  symbol TEXT NOT NULL,
  side SMALLINT NOT NULL,
  price NUMERIC NOT NULL,
  size NUMERIC NOT NULL,
  timestamp BIGINT NOT NULL
);